### ISSUE TITLE
APIC Dev Jam Lab 1 - Inventory.yaml doesn't work

### ISSUE THREAD

**Issue by ccavazos** [ibm-garage-tsa/cp4i-demohub#3]
With the latest release of APIC v10.0.2.0 the Dev Jam Lab 1 doesn't work anymore. The inventory.yaml is missing some fields that cause APIC to reject the import. 

Here is a screenshot of the error:
![APIC V10 2021 Import Error](https://user-images.githubusercontent.com/1228300/116925271-d3a09180-ac0d-11eb-8340-21c4cfc76adb.png)

In order to solve the error the yaml needs to add the following fields:

```yaml
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    target-url:
      value: 'http://example.com/operation-name'
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
  gateway: datapower-api-gateway
  type: rest
```

I'm not sure if this is a bug with APIC since the inventory.yaml is a standard swagger 2.0 doc but I figure I start by raising it here.
